# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: DownloadSecureFile@1
    name: uwpCert
    inputs:
      secureFile: 'Todo.UWP_TemporaryKey.pfx'

  - task: PowerShell@2
    displayName: install cert
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Start adding the PFX file to the certificate store."

        $pfxpath = '$(uwpCert.secureFilePath)'
        $password = '$(cert.pwd)'
        
        Add-Type -AssemblyName System.Security
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
        $cert.Import($pfxpath, $password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
        $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
        $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
        $store.Add($cert)
        $store.Close()

  - task: GitVersion@5
    inputs:
      runtime: 'full'
      preferBundledVersion: false
      updateAssemblyInfo: true

  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.SemVer)

  - task: NuGetToolInstaller@1
    inputs:
        versionSpec: '5.3.0'

  - task: NuGetCommand@2
    inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'

  - task: VSBuild@1
    inputs:
        solution: '**\*.sln'
        configuration: 'Release'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/LiteDB.StateStore.csproj'
      nobuild: true
      includesymbols: true
      arguments: /p:SymbolPackageFormat=snupkg

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'artifacts'
      publishLocation: 'Container'