# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'Todo.UWP_TemporaryKey.pfx'

  - task: CopyFiles@2
    inputs:
      Contents: '*.pfx'
      SourceFolder: '$(Agent.TempDirectory)'
      TargetFolder: './Demo/Todo.UWP/'

  - task: GitVersion@5
    inputs:
      runtime: 'full'
      preferBundledVersion: false
      updateAssemblyInfo: true

  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.SemVer)

  - task: NuGetToolInstaller@1
    inputs:
        versionSpec: '5.3.0'

  - task: NuGetCommand@2
    inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'

  - task: VSBuild@1
    inputs:
        solution: '**\*.sln'
        configuration: 'Release'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/LiteDB.StateStore.csproj'
      nobuild: true
      includesymbols: true
      arguments: /p:SymbolPackageFormat=snupkg

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'artifacts'
      publishLocation: 'Container'